#
#     ▄█          ▄████████    ▄████████    ▄████████         ▄█    █▄     ▄█      ███             ▄███████▄    ▄████████    ▄████████     ███      ▄█   ▄████████  ▄█          ▄████████
#    ███         ███    ███   ███    ███   ███    ███        ███    ███   ███  ▀█████████▄        ███    ███   ███    ███   ███    ███ ▀█████████▄ ███  ███    ███ ███         ███    ███
#    ███         ███    █▀    ███    █▀    ███    █▀         ███    ███   ███▌    ▀███▀▀██        ███    ███   ███    ███   ███    ███    ▀███▀▀██ ███▌ ███    █▀  ███         ███    █▀
#    ███        ▄███▄▄▄       ███          ███              ▄███▄▄▄▄███▄▄ ███▌     ███   ▀        ███    ███   ███    ███  ▄███▄▄▄▄██▀     ███   ▀ ███▌ ███        ███        ▄███▄▄▄
#    ███       ▀▀███▀▀▀     ▀███████████ ▀███████████      ▀▀███▀▀▀▀███▀  ███▌     ███          ▀█████████▀  ▀███████████ ▀▀███▀▀▀▀▀       ███     ███▌ ███        ███       ▀▀███▀▀▀
#    ███         ███    █▄           ███          ███        ███    ███   ███      ███            ███          ███    ███ ▀███████████     ███     ███  ███    █▄  ███         ███    █▄
#    ███▌    ▄   ███    ███    ▄█    ███    ▄█    ███        ███    ███   ███      ███            ███          ███    ███   ███    ███     ███     ███  ███    ███ ███▌    ▄   ███    ███
#    █████▄▄██   ██████████  ▄████████▀   ▄████████▀         ███    █▀    █▀      ▄████▀         ▄████▀        ███    █▀    ███    ███    ▄████▀   █▀   ████████▀  █████▄▄██   ██████████
#    ▀                                                                                                                      ███    ███                             ▀
#

less-hit-particle:

  # Liste des paramètres du plugin
  settings:
    # Paramètre des indices de quantité de particule qui apparaîtront
    float:
      # Indice de quantité de particule des coups critiques (défaut → 55.0)
      critical-hit: 55.0
      # Indice de quantité de particule des coups avec des items enchantés (défaut → 15.0)
      magical-hit: 15.0